# Generated by Django 3.2 on 2021-04-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_billingprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
