# Generated by Django 3.1.6 on 2021-04-03 22:19

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ImageField(blank=True, upload_to=items.models.upload_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('category', models.CharField(choices=[('0', 'Technology'), ('1', 'Home & Garden'), ('2', 'Parts & Accessories'), ('3', 'Toys'), ('4', 'Music'), ('5', 'Jewelry'), ('6', 'Clothes'), ('7', 'Makeups & Beauty'), ('8', 'Others')], default='Others', max_length=20)),
            ],
        ),
    ]
