# Generated by Django 3.1.6 on 2021-03-02 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
