# Generated by Django 3.1.6 on 2021-03-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_remove_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Category',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
