# Generated by Django 3.1.6 on 2021-03-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_auto_20210302_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Category',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('0', 'Technology'), ('1', 'Home & Garden'), ('2', 'Parts & Accessories'), ('3', 'Toys'), ('4', 'Music'), ('5', 'Jewelry'), ('6', 'Clothes'), ('7', 'Makeups & Beauty'), ('8', 'Others')], default='Others', max_length=20),
        ),
    ]
