# Generated by Django 3.1.6 on 2021-03-29 14:49

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_auto_20210329_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.ImageField(blank=True, upload_to=items.models.upload_image_path),
        ),
    ]
